# Generated by Django 5.2.4 on 2025-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
