# Generated by Django 5.2.4 on 2025-08-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0002_resident_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='phone_number',
        ),
    ]
