# Generated by Django 5.2.4 on 2025-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0003_remove_resident_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='message',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
